#generated by xsl for iphone
subfont=C:\Windows\Fonts\msyh.ttf
subcp=cp936
ofps=30
vf=scale=-10:480,harddup
of=lavf=yes
lavfopts=format=ipod
channels=2
srate=48000
oac=faac=yes
faacopts=mpeg=4:object=2:br=128:raw=yes
ovc=x264=yes
x264encopts=cabac=no:global_header=yes:bitrate=512:level_idc=30:vbv_bufsize=2000:vbv_maxrate=960:frameref=6:me=hex:threads=auto:trellis=1
